[book]
authors = ["SCTT Team"]
language = "en"
multilingual = false
src = "book"
title = "Smooth Cubical Type Theory"
description = "A comprehensive guide to Smooth Cubical Type Theory, bridging homotopy type theory and differential geometry"

[preprocessor.katex]

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/TensorHusker/SCTT"
edit-url-template = "https://github.com/TensorHusker/SCTT/edit/main/{path}"
site-url = "https://sctt.space/"
cname = "sctt.space"

[output.html.print]
enable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.redirect]
"/index.html" = "../index.html"