[package]
name = "sctt-physics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Physics simulation using SCTT"

[dependencies]
sctt-core = { path = "../sctt-core" }
sctt-smooth = { path = "../sctt-smooth" }
nalgebra.workspace = true
anyhow.workspace = true